#!/bin/bash
# Archive Script: Move legacy files to trash/archive
# Generated by Phantom Arbiter Refactor

ARCHIVE_DIR="trash/archive/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$ARCHIVE_DIR"

echo "Archiving legacy files to $ARCHIVE_DIR..."

# Legacy sync execution (now decomposed into execution pipeline)
if [ -f "src/delta_neutral/sync_execution_old.py" ]; then
    mv "src/delta_neutral/sync_execution_old.py" "$ARCHIVE_DIR/"
    echo "  - Archived: sync_execution_old.py"
fi

# Legacy order builder (now in instruction_factory.py)
if [ -f "src/delta_neutral/drift_order_builder_old.py" ]; then
    mv "src/delta_neutral/drift_order_builder_old.py" "$ARCHIVE_DIR/"
    echo "  - Archived: drift_order_builder_old.py"
fi

# Legacy core engines (orphaned)
for file in src/core/*Engine*.py; do
    if [ -f "$file" ]; then
        mv "$file" "$ARCHIVE_DIR/"
        echo "  - Archived: $(basename $file)"
    fi
done

# Legacy folder
if [ -d "src/legacy" ]; then
    mv "src/legacy" "$ARCHIVE_DIR/"
    echo "  - Archived: src/legacy/"
fi

echo ""
echo "Archive complete!"
echo "Files moved to: $ARCHIVE_DIR"
echo ""
echo "To restore, run:"
echo "  mv $ARCHIVE_DIR/* ."
