# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from datafeed import market_data_pb2 as datafeed_dot_market__data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in datafeed/market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """Market Data Service - Front of the line data ingestion
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPrices = channel.unary_stream(
                '/phantom.datafeed.MarketDataService/StreamPrices',
                request_serializer=datafeed_dot_market__data__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=datafeed_dot_market__data__pb2.PriceUpdate.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/phantom.datafeed.MarketDataService/GetSnapshot',
                request_serializer=datafeed_dot_market__data__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=datafeed_dot_market__data__pb2.MarketSnapshot.FromString,
                _registered_method=True)
        self.SubscribeTopic = channel.unary_stream(
                '/phantom.datafeed.MarketDataService/SubscribeTopic',
                request_serializer=datafeed_dot_market__data__pb2.TopicRequest.SerializeToString,
                response_deserializer=datafeed_dot_market__data__pb2.MarketEvent.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/phantom.datafeed.MarketDataService/HealthCheck',
                request_serializer=datafeed_dot_market__data__pb2.Empty.SerializeToString,
                response_deserializer=datafeed_dot_market__data__pb2.HealthResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """Market Data Service - Front of the line data ingestion
    """

    def StreamPrices(self, request, context):
        """Stream real-time price updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Get current market snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTopic(self, request, context):
        """Subscribe to specific topics (whale, discovery, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPrices': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPrices,
                    request_deserializer=datafeed_dot_market__data__pb2.SubscribeRequest.FromString,
                    response_serializer=datafeed_dot_market__data__pb2.PriceUpdate.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=datafeed_dot_market__data__pb2.SnapshotRequest.FromString,
                    response_serializer=datafeed_dot_market__data__pb2.MarketSnapshot.SerializeToString,
            ),
            'SubscribeTopic': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTopic,
                    request_deserializer=datafeed_dot_market__data__pb2.TopicRequest.FromString,
                    response_serializer=datafeed_dot_market__data__pb2.MarketEvent.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=datafeed_dot_market__data__pb2.Empty.FromString,
                    response_serializer=datafeed_dot_market__data__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'phantom.datafeed.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('phantom.datafeed.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Market Data Service - Front of the line data ingestion
    """

    @staticmethod
    def StreamPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/phantom.datafeed.MarketDataService/StreamPrices',
            datafeed_dot_market__data__pb2.SubscribeRequest.SerializeToString,
            datafeed_dot_market__data__pb2.PriceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phantom.datafeed.MarketDataService/GetSnapshot',
            datafeed_dot_market__data__pb2.SnapshotRequest.SerializeToString,
            datafeed_dot_market__data__pb2.MarketSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/phantom.datafeed.MarketDataService/SubscribeTopic',
            datafeed_dot_market__data__pb2.TopicRequest.SerializeToString,
            datafeed_dot_market__data__pb2.MarketEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/phantom.datafeed.MarketDataService/HealthCheck',
            datafeed_dot_market__data__pb2.Empty.SerializeToString,
            datafeed_dot_market__data__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
