# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apps/datafeed/src/datafeed/market_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'apps/datafeed/src/datafeed/market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,apps/datafeed/src/datafeed/market_data.proto\x12\x10phantom.datafeed\"\x07\n\x05\x45mpty\"L\n\x10SubscribeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\r\n\x05mints\x18\x02 \x03(\t\x12\x18\n\x10include_metadata\x18\x03 \x01(\x08\"*\n\x0fSnapshotRequest\x12\x17\n\x0fmax_age_seconds\x18\x01 \x01(\x05\"\x1d\n\x0cTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\xc8\x01\n\x0bPriceUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04mint\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x12\n\nvolume_24h\x18\x04 \x01(\x01\x12\x11\n\tliquidity\x18\x05 \x01(\x01\x12\x17\n\x0fprice_change_1h\x18\x06 \x01(\x01\x12\x18\n\x10price_change_24h\x18\x07 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x08 \x01(\x03\x12\x0e\n\x06source\x18\t \x01(\t\x12\x0c\n\x04slot\x18\n \x01(\x05\"o\n\x0eMarketSnapshot\x12-\n\x06prices\x18\x01 \x03(\x0b\x32\x1d.phantom.datafeed.PriceUpdate\x12\x18\n\x10snapshot_time_ms\x18\x02 \x01(\x03\x12\x14\n\x0csource_count\x18\x03 \x01(\x05\"{\n\x0bMarketEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0c\n\x04mint\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x15\n\rmetadata_json\x18\x05 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"\x82\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x17\n\x0fwss_connections\x18\x02 \x01(\x05\x12\x17\n\x0fsymbols_tracked\x18\x03 \x01(\x05\x12\x16\n\x0e\x61vg_latency_ms\x18\x04 \x01(\x01\x12\x16\n\x0euptime_seconds\x18\x05 \x01(\x03\x32\xd9\x02\n\x11MarketDataService\x12S\n\x0cStreamPrices\x12\".phantom.datafeed.SubscribeRequest\x1a\x1d.phantom.datafeed.PriceUpdate0\x01\x12R\n\x0bGetSnapshot\x12!.phantom.datafeed.SnapshotRequest\x1a .phantom.datafeed.MarketSnapshot\x12Q\n\x0eSubscribeTopic\x12\x1e.phantom.datafeed.TopicRequest\x1a\x1d.phantom.datafeed.MarketEvent0\x01\x12H\n\x0bHealthCheck\x12\x17.phantom.datafeed.Empty\x1a .phantom.datafeed.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apps.datafeed.src.datafeed.market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=66
  _globals['_EMPTY']._serialized_end=73
  _globals['_SUBSCRIBEREQUEST']._serialized_start=75
  _globals['_SUBSCRIBEREQUEST']._serialized_end=151
  _globals['_SNAPSHOTREQUEST']._serialized_start=153
  _globals['_SNAPSHOTREQUEST']._serialized_end=195
  _globals['_TOPICREQUEST']._serialized_start=197
  _globals['_TOPICREQUEST']._serialized_end=226
  _globals['_PRICEUPDATE']._serialized_start=229
  _globals['_PRICEUPDATE']._serialized_end=429
  _globals['_MARKETSNAPSHOT']._serialized_start=431
  _globals['_MARKETSNAPSHOT']._serialized_end=542
  _globals['_MARKETEVENT']._serialized_start=544
  _globals['_MARKETEVENT']._serialized_end=667
  _globals['_HEALTHRESPONSE']._serialized_start=670
  _globals['_HEALTHRESPONSE']._serialized_end=800
  _globals['_MARKETDATASERVICE']._serialized_start=803
  _globals['_MARKETDATASERVICE']._serialized_end=1148
# @@protoc_insertion_point(module_scope)
